partial:
  by: target
project_name: opentelemetry-collector-releases
env:
  - COSIGN_YES=true
builds:
  - id: otelcol
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64le
      - s390x
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: s390x
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: s390x
    dir: _build
    binary: otelcol
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
archives:
  - id: otelcol
    builds:
      - otelcol
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
nfpms:
  - package_name: otelcol
    contents:
      - src: otelcol.service
        dst: /lib/systemd/system/otelcol.service
      - src: otelcol.conf
        dst: /etc/otelcol/otelcol.conf
        type: config|noreplace
      - src: config.yaml
        dst: /etc/otelcol/config.yaml
        type: config
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    id: otelcol
    builds:
      - otelcol
    formats:
      - apk
      - deb
      - rpm
    maintainer: The OpenTelemetry Collector maintainers <cncf-opentelemetry-maintainers@lists.cncf.io>
    description: OpenTelemetry Collector - otelcol
    license: Apache 2.0
checksum:
  name_template: '{{ .ProjectName }}_otelcol_checksums.txt'
dockers:
  - goos: linux
    goarch: "386"
    dockerfile: Dockerfile
    image_templates:
      - thelmuth34/opentelemetry-collector:{{ .Version }}-386
      - thelmuth34/opentelemetry-collector:latest-386
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-386
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:latest-386
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/386
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
    use: buildx
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - thelmuth34/opentelemetry-collector:{{ .Version }}-amd64
      - thelmuth34/opentelemetry-collector:latest-amd64
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-amd64
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:latest-amd64
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
    use: buildx
  - goos: linux
    goarch: arm
    goarm: "7"
    dockerfile: Dockerfile
    image_templates:
      - thelmuth34/opentelemetry-collector:{{ .Version }}-armv7
      - thelmuth34/opentelemetry-collector:latest-armv7
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-armv7
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:latest-armv7
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/arm/v7
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
    use: buildx
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - thelmuth34/opentelemetry-collector:{{ .Version }}-arm64
      - thelmuth34/opentelemetry-collector:latest-arm64
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-arm64
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:latest-arm64
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
    use: buildx
  - goos: linux
    goarch: ppc64le
    dockerfile: Dockerfile
    image_templates:
      - thelmuth34/opentelemetry-collector:{{ .Version }}-ppc64le
      - thelmuth34/opentelemetry-collector:latest-ppc64le
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-ppc64le
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:latest-ppc64le
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/ppc64le
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
    use: buildx
  - goos: linux
    goarch: s390x
    dockerfile: Dockerfile
    image_templates:
      - thelmuth34/opentelemetry-collector:{{ .Version }}-s390x
      - thelmuth34/opentelemetry-collector:latest-s390x
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-s390x
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:latest-s390x
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/s390x
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
    use: buildx
docker_manifests:
  - name_template: thelmuth34/opentelemetry-collector:{{ .Version }}
    image_templates:
      - thelmuth34/opentelemetry-collector:{{ .Version }}-386
      - thelmuth34/opentelemetry-collector:{{ .Version }}-amd64
      - thelmuth34/opentelemetry-collector:{{ .Version }}-armv7
      - thelmuth34/opentelemetry-collector:{{ .Version }}-arm64
      - thelmuth34/opentelemetry-collector:{{ .Version }}-ppc64le
      - thelmuth34/opentelemetry-collector:{{ .Version }}-s390x
  - name_template: thelmuth34/opentelemetry-collector:latest
    image_templates:
      - thelmuth34/opentelemetry-collector:latest-386
      - thelmuth34/opentelemetry-collector:latest-amd64
      - thelmuth34/opentelemetry-collector:latest-armv7
      - thelmuth34/opentelemetry-collector:latest-arm64
      - thelmuth34/opentelemetry-collector:latest-ppc64le
      - thelmuth34/opentelemetry-collector:latest-s390x
  - name_template: ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}
    image_templates:
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-386
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-amd64
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-armv7
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-arm64
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-ppc64le
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-s390x
  - name_template: ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:latest
    image_templates:
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:latest-386
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:latest-amd64
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:latest-armv7
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:latest-arm64
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:latest-ppc64le
      - ghcr.io/tylerhelmuth/opentelemetry-collector-releases/opentelemetry-collector:latest-s390x
signs:
  - cmd: cosign
    args:
      - sign-blob
      - --output-signature
      - ${artifact}.sig
      - --output-certificate
      - ${artifact}.pem
      - ${artifact}
    signature: ${artifact}.sig
    artifacts: all
    certificate: ${artifact}.pem
docker_signs:
  - args:
      - sign
      - ${artifact}
    artifacts: all
sboms:
  - id: archive
    artifacts: archive
  - id: package
    artifacts: package
