name: Continuous Integration - Core - GoReleaser

on:
  push:
    branches: [main]
    paths:
      - "distributions/otelcol/**"
      - "cmd/**"
      - ".github/**"
      - "scripts/**"
      - "Makefile"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches: [main]
    paths:
      - "distributions/otelcol/**"
      - "cmd/**"
      - ".github/**"
      - "scripts/**"
      - "Makefile"
      - "go.mod"
      - "go.sum"


jobs:
  check-goreleaser:
    name: Continuous Integration - Core - GoReleaser
    uses: ./.github/workflows/base-ci-goreleaser.yaml
    with:
      distribution: otelcol
    secrets: inherit
